import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per navbar section. Items inside each folder are ordered by `sidebar_position`.
const sidebars: SidebarsConfig = {
  getStarted: [
    {type: 'category', label: 'Introduction', collapsed: false, items: [{type: 'autogenerated', dirName: 'intro'}]},
    {type: 'category', label: 'Getting started', collapsed: false, items: [{type: 'autogenerated', dirName: 'getting-started'}]},
  ],
  userGuide: [{type: 'autogenerated', dirName: 'user-guide'}],
  deploy: [{type: 'autogenerated', dirName: 'deploy'}],
  developers: [{type: 'autogenerated', dirName: 'developers'}],
  reference: [{type: 'autogenerated', dirName: 'reference'}],
};

export default sidebars;
